export type PartnerUniversity = {
  name: string;
  logo: string;
};

export const partnerUniversities: PartnerUniversity[] = [
  { name: "Conestoga College", logo: "/images/universities/conestoga.png" },
  { name: "Seneca Polytechnic", logo: "/images/universities/seneca.png" },
  { name: "Lambton College", logo: "/images/universities/lambton.png" },
  { name: "Cape Breton University", logo: "/images/universities/cape-breton.png" },
  { name: "University of Windsor", logo: "/images/universities/windsor.png" },
  { name: "University of Hertfordshire", logo: "/images/universities/hertfordshire.png" },
  { name: "Coventry University", logo: "/images/universities/coventry.png" },
  { name: "University of East London", logo: "/images/universities/east-london.png" },
  { name: "Anglia Ruskin University", logo: "/images/universities/anglia-ruskin.png" },
  { name: "University of Greenwich", logo: "/images/universities/greenwich.png" },
  { name: "Deakin University", logo: "/images/universities/deakin.png" },
  { name: "Griffith University", logo: "/images/universities/griffith.png" },
  { name: "Curtin University", logo: "/images/universities/curtin.png" },
  { name: "University of Wollongong", logo: "/images/universities/wollongong.png" },
  { name: "La Trobe University", logo: "/images/universities/latrobe.png" },
  { name: "IU International University", logo: "/images/universities/iu.png" },
  { name: "University of Europe for Applied Sciences", logo: "/images/universities/ue.png" },
  { name: "GISMA Business School", logo: "/images/universities/gisma.png" },
  { name: "University of Malta", logo: "/images/universities/malta.png" },
  { name: "Istanbul University", logo: "/images/universities/istanbul.png" },
  { name: "Boğaziçi University", logo: "/images/universities/bogazici.png" },
  { name: "Sorbonne University", logo: "/images/universities/sorbonne.png" },
  { name: "University of Amsterdam", logo: "/images/universities/amsterdam.png" },
  { name: "University of Bologna", logo: "/images/universities/bologna.png" },
  { name: "University of Barcelona", logo: "/images/universities/barcelona.png" },
  { name: "University of Vienna", logo: "/images/universities/vienna.png" },
  { name: "Charles University", logo: "/images/universities/charles.png" },
  { name: "KU Leuven", logo: "/images/universities/leuven.png" },
  { name: "University of Warsaw", logo: "/images/universities/warsaw.png" },
  { name: "University of Zurich", logo: "/images/universities/zurich.png" },
  { name: "Auckland University of Technology", logo: "/images/universities/aut.png" },
  { name: "Massey University", logo: "/images/universities/massey.png" },
  { name: "University of Waikato", logo: "/images/universities/waikato.png" },
  { name: "Lincoln University", logo: "/images/universities/lincoln.png" },
  { name: "Unitec", logo: "/images/universities/unitec.png" },
  { name: "Arizona State University", logo: "/images/universities/asu.png" },
  { name: "University of Cincinnati", logo: "/images/universities/cincinnati.png" },
  { name: "Wichita State University", logo: "/images/universities/wichita.png" },
  { name: "Monroe College", logo: "/images/universities/monroe.png" },
  { name: "California State University, East Bay", logo: "/images/universities/csueb.png" },
];
